### ISSUE TITLE
Throws an error when strict-di is on

### ISSUE THREAD

**Issue by jbalboni** [wbuchwalter/ng-redux#10]
The latest release throws an error if you have strict-di turned on in your app. It looks like it's because $injector is now used by ngReduxProvider.$get (https://github.com/wbuchwalter/ng-redux/blob/master/src/components/ngRedux.js#L29). Add this after that function fixes it:

    this.$get.$inject = ['$injector']

I can submit a PR later if that helps.

**Comment by wbuchwalter** [comment]
Yep, forgot that!
You can PR, otherwise i'll fix it tomorrow.
thanks!

**Comment by wbuchwalter** [comment]
Fixed, this will be released on npm along 1.0.0, with the API refactoring (breaking changes) in the next few days.
Thanks.
