### ISSUE TITLE
createStoreWith without middleware fails

### ISSUE THREAD

**Issue by simplesmiler** [wbuchwalter/ng-redux#13]
If you call `$ngReduxProvider.createStoreWith` without specifying middleware, then `$ngRedux` will throw `Cannot read property 'Symbol(Symbol.iterator)' of undefined` upon injection.

Proposed fix: make `$ngReduxProvider.createStoreWith` take `[]` as default parameter for middleware.

Should I make a pull request?

---

Chrome 44.0.2403.157

**Comment by wbuchwalter** [comment]
Good catch!
Feel free to PR, otherwise i'll correct that later today/tomorrow.
Thanks!

**Comment by simplesmiler** [comment]
:+1:
