### ISSUE TITLE
$scope may not contain the controller-as-key during controller activation (ui-router)

### ISSUE THREAD

**Issue by simplesmiler** [wbuchwalter/ng-redux#14]
While playing with ng-redux I stumbled upon a case when `findControllerAsKey` is not able to figure out the controller-as-key, because the key does not exist in the $scope yet.

Repro: http://requirebin.com/?gist=559a4edcfbee14c79e27

- angular 1.4.5, ui-router 0.2.15
- ng-redux 1.0.0-rc.4
- Chrome 44.0.2403.157

The workaround is to delay the `$ngRedux.connect` call a bit, for example with `$scope.$evalAsync` (commented out in the repro).

I'm not sure what causes this. Is it worth looking into, considering https://github.com/wbuchwalter/ng-redux/issues/12 and `bc-1.0.0` changes?

**Comment by wbuchwalter** [comment]
Hey Denis,
No, it's not really worth looking into it aside educational purpose ;)
`findControllerAsKey` and it's behavior will totally disappear in the next version that should be out in the next days.
Hopefully this will be the last round of significant breaking changes for a while.
I'll let this issue open until the next release.
Thanks!

**Comment by simplesmiler** [comment]
Ok, I'll be be using `bc-1.0.0` for now then.
`ng-redux` is cool!

**Comment by wbuchwalter** [comment]
Thanks ;)
The documentation on `bc-1.0.0` is not perfect, so if you have any problem feel free to open an issue or you can find me on [slack](https://reactiflux.slack.com/)!

**Comment by simplesmiler** [comment]
Yay! Will play with 2.0 it tomorrow.
