### ISSUE TITLE
Angular 2

### ISSUE THREAD

**Issue by jimthedev** [wbuchwalter/ng-redux#2]
Hi William,

Have you tried this with Angular 2 at all to see if the concepts and the code would plug in? 

Jim

**Comment by wbuchwalter** [comment]
Hey Jim!
It's on my todo list, but didn't found time for that yet.
If someone can help me on that that would be cool, otherwise I'll try to do that soon.

**Comment by jimthedev** [comment]
Awesome. I think Patrick JS from the Angular team has done some work on this already and he is going to create a repo to collaborate on. It might be cool to use your work as a base or even to share some core code if it is framework agnostic.

**Comment by wbuchwalter** [comment]
Hey @jimthedev,
I started another repo ([ng2-redux](https://github.com/wbuchwalter/ng2-redux)) for Angular 2 bindings. 
It includes a simple [example application](https://github.com/wbuchwalter/ng2-redux/tree/master/examples/counter) based on Patrick JS [counter app](https://github.com/gdi2290/redux/tree/angular2-counter/examples/angular2-counter).

It's very basic for now and can be improved a lot. Feedback welcome :)
