### ISSUE TITLE
mapDispatchToTarget issues when using middleware and actions that return non-plain objects

### ISSUE THREAD

**Issue by e-schultz** [wbuchwalter/ng-redux#22]
Setting up a sample application to use redux-ui-router, 

Have a controller like this:

```javascript
export default class MainController {
  constructor($ngRedux, ngUiRouterActions, $scope) {
    let _onUpdate = (state) => ({
      globalState: state
    });
    let disconnect = $ngRedux.connect(_onUpdate, ngUiRouterActions)(this);
    $scope.$on('$destroy', () => disconnect());

  }

}
```

In the template I have:

```html
<a ng-click="main.stateGo('app.orders.pending')">Pending Orders</a>
```

When I click the link, I get an error from redux saying actions must return plain JS objects, to use non-JS objects - to use a middleware.

However, if I put the following into my controller

```javascript
this.stateGoTest = (state) => ngUiRouterActions.stateGo(state);
```

and change my template to use main.stateGoTest 

Then the action fires, and I don't get any errors. Interestingly though - even with the errors that redux logs, looks like the event fires anyways.

Also tried something like:

```javascript
$ngRedux.connect(_onUpdate,ngUiRouterActions)((state, dispatch) => {
this.stateGo = dispatch.stateGo; // error
this.stateGo = (state) => dispatch.stateGo(state); // error
this.stateGo = (state) => ngUiRouterActions.stateGo(state); // works
})
```
I do have the thunk middleware as part of my $ngProvider.createStoreWith -  so not sure what is going on.

I'll try and get a smaller stand-alone example together later if needed.

**Comment by wbuchwalter** [comment]
I would love a stand alone example indeed!
I've been fiddling a little bit with redux-ui-router but couldn't reproduce, so i'm probably missing something  from your implementation.

**Comment by e-schultz** [comment]
Think I found the issue,

the service in redux-ui-router returns

```javascript
return redux.bindActionCreators(actionCreator, $ngRedux.dispatch);
```

If I change it to simply return 'actionCreator', then the mapDispatchToTarget works - so I think if things have already been run through bindActionCreators, then doing it again causes the issue.

Might adjust redux-ui-router to have the option of doing the bindActionCreators in there, or simply returning them normally. Maybe make it a provider and a setting that can be run during config, but that's an issue for the other repo.

**Comment by wbuchwalter** [comment]
Makes sense. Calling `bindActionCreators` twice would wrap your action in two dispatch.
So when Redux unwrap it once, it expects an object but instead receive ` dispatch => { ... } ` which causes the error.
I wonder if it would be a good convention to just always delegate the responsibility of binding action creators to the user.
I started playing with ui-redux-router yesterday, so I will try to give you guys some feedback.
