### ISSUE TITLE
shallowEqual need to be enhanced

### ISSUE THREAD

**Issue by sandwich99** [wbuchwalter/ng-redux#23]
shallowEqual always return false, cause angular.js create $$hashkey for each vm

![image](https://cloud.githubusercontent.com/assets/1179783/9895131/91accff0-5c5e-11e5-9df9-bcde96beff10.png)

```javascript

   var keysA = Object.keys(objA);
   var keysB = Object.keys(objB);

   if (keysA.length !== keysB.length) {
     return false;
   }

```

**Comment by wbuchwalter** [comment]
Hey,
This is not on every vm, only on vm inside a `ng-repeat`.
But you are right that it should be handled by ngRedux.

In the mean time, if you have performance issues because of that, you can use `track by` which will remove the need for angular to add a `$$hashKey`.

e.g:
```html
<div ng-repeat="employee in vm.employees track by employee.id">
    [...]
</div>
```
