### ISSUE TITLE
Question: How to call a method after state has been mapped to this

### ISSUE THREAD

**Issue by fifafu** [wbuchwalter/ng-redux#28]
Hi William,

thank you very much for creating and maintaining ng-redux, it has helped me a lot!

I have one question:
What is the best approach if I need to call some method after the state has changed and was mapped to this? If I put the method invocation in the mapDispatchToTarget it'll be called before the state has been mapped.

Currently I'm passing a function as target to $ngRedux.connect, however then I have to call     _.assign(target, StateSlice, dispatch) by myself. This doesn't seem to be a nice solution (or is it?).

I'm pretty new to all this, so please excuse if this is a silly question.

Best,
Andreas

**Comment by wbuchwalter** [comment]
Hey Andreas!

Passing a function as target is indeed the right way to do it.

Basically $ngRedux offers you two ways of binding data to your controller:
* by passing an object as target (usually your controller), and letting $ngRedux merging everything on it. This is the standard way.
* by passing a callback. This is usually used if you need some additional flexibility, the responsibility to map the selectedState and the action creators to the controller is thus indeed delegated to you.  In your case you want to use that.

Note that ideally your components should be as dumb as possible, so calling a method on each state change should be done as little as possible. But if you need to do it, use the callback.

If you are okay with showing your code, I may be able to give you more specific advice.
Thanks!

**Comment by fifafu** [comment]
Hi William,

thanks, just wanted to be sure this is the correct way :-)
I needed to call a method on an external plugin used in one of my components, but it's working fine with the callback.

One other, unrelated, question: is it possible to to use the angular $http service in Redux actions? The Redux documentation says it's okay to do http requests in actions when using the thunk middleware, however I'm not sure how I would inject $http.

For example the redux documentation has this sample action:

function fetchPosts(reddit) {
  return dispatch => {
    dispatch(requestPosts(reddit));
    return fetch(`http://www.reddit.com/r/${reddit}.json`)
      .then(req => req.json())
      .then(json => dispatch(receivePosts(reddit, json)));
  }
}

I'm currently using a similar middleware to this: https://github.com/e-schultz/ng-redux-nhl-stats-example/blob/master/src/middleware/http/http-middleware.js however in some cases it would be useful to do requests directly in an action using the thunk middleware.

Thanks!!
Andreas

**Comment by fifafu** [comment]
Ah, I think I figured this out using "bindActionCreators" in an Angular Factory like this:
```
import { bindActionCreators } from 'redux';

export default function httpActionService($ngRedux, $http){
    let actionCreator = {
        doSomeStuff: () => {
            return function (dispatch) {
                dispatch(something);
                
                return $http('http://www.test.de')
                    .then(json =>
                        dispatch(something)
                );
            };
        }
    }
    return bindActionCreators(actionCreator, $ngRedux.dispatch);
}

httpActionService.$inject = ['$ngRedux', '$http'];

```

Then I can just inject this service into my controllers and call the methods defined.
Is this approach ok?

**Comment by wbuchwalter** [comment]
Hey Andreas,
You have two way of accomplishing that:
* The way you showed here: binding your action creators in a service and making your http call there
* Or you can create your own middleware and inject $http into it. e.g, you can copy thunkMiddleware and just replace fetch by $http. To do that, just declare your middleware as a service (i'll call it `$httpMiddleware` here) and create your store like this : `createStoreWith(reducer, ['$httpMiddleware', anotherMiddleware])`. See [this part of the doc](https://github.com/wbuchwalter/ng-redux#createstorewithreducer-middlewares-storeenhancers) for more info.

Pick the way you like the most, both are ok.

**Comment by fifafu** [comment]
Cool, thanks a lot! For now all my questions are answered :-)

**Comment by wbuchwalter** [comment]
:+1:

**Comment by fifafu** [comment]
I have one more general question :-)

What are best practices on how to work with ng-redux in combination with the ui-router? E.g. when a http requests succeeds I want to go to a different state. Would I do this using a middleware?

**Comment by wbuchwalter** [comment]
Hey!
You can take a look at [redux-ui-router](https://github.com/neilff/redux-ui-router/).
There is also this [sample app](https://github.com/e-schultz/ng-summit-redux) that use redux-ui-router, so you can check how it works.
It's indeed using a middleware underneath.
