### ISSUE TITLE
Initial store state

### ISSUE THREAD

**Issue by jacobrask** [wbuchwalter/ng-redux#30]
Hi, the Redux method to create a store is `createStore(reducer, [initialState])`. Is there a way in ng-redux to supply an initial state to the created store? Otherwise you can't seed the application from the server or localStorage.

I guess this relates to #19 a bit.

**Comment by wbuchwalter** [comment]
Hey Jacob,
Yea it's somewhat related, ideally ngRedux wouldn't handle the store creation at all, but this proved tricky with injectable middlewares.
That said, for your specific issue, a paramater could be added to `createStoreWith` in last position that would take the initialState and then passed to Redux's `createStore`.
I don't see any problem doing that.
I'll try to do that in the next few days, but feel free to make a PR if you need it before that!
Thanks

**Comment by wbuchwalter** [comment]
Fixed (At last) via #52.
Thanks @D34THWINGS
