### ISSUE TITLE
cannot run example  (Cannot GET /)

### ISSUE THREAD

**Issue by p2227** [wbuchwalter/ng-redux#39]
i just

 git clone  https://github.com/wbuchwalter/ng-redux

run` npm install` in  examples\async

and `npm start`

and open the browser and type http://localhost:8080/

but it got  `Cannot GET /`

**Comment by p2227** [comment]
it can run open
http://localhost:8080/index.html

**Comment by wbuchwalter** [comment]
Hey!
I just tried and I can't reproduce your issue, both `http://localhost:8080/` and `http://localhost:8080/index.html` work correctly for me!
