### ISSUE TITLE
Role of angular services in redux

### ISSUE THREAD

**Issue by ksachdeva** [wbuchwalter/ng-redux#49]
Hi William,

I am very new to redux (a day old :) ) and while I have started to get the feel for the problems it (redux) may help solve I am having some doubts/confusion around the role of angular services/factories in this new architecture.

The 'state' of a view or even entire application is typically managed by angular services/models in a traditional angular application

Would help if you could throw some light on hat limited use of angular services would be with redux/ng-redux

Regards & thanks
Kapil

**Comment by wbuchwalter** [comment]
Hey Kapil,

In a traditional MVVM app, there is no real enforcement of where to keep the state of your application. Some people had repositories as a service, some simply kept the state of each view in it's VM etc.

Redux, on the other hand, forces you to keep your state in one single place, the store.
This means that you are not responsible to create any angular service to manage your state. 

`ng-redux` in itself is still exposed to the rest of your application via a service, and you'll probably still use services to make your backend calls, or to access your action creators (not mandatory).

I'm not sure I really answered your question, so feel free to rephrase your question if it's still unclear!
Thanks

**Comment by wbuchwalter** [comment]
I'm closing this issue, since it's not an issue, but feel free to continue the discussion here.

**Comment by michalpanek** [comment]
I have a question. If I have in my app ng-redux store, should I get the data from backend through the services, and update store from controller, or I should call the store for data instead of service, and store get data calling services, which sending requests to backend api?
