### ISSUE TITLE
Update support for redux-devtools 3.x or chrome extension redux dev tools support

### ISSUE THREAD

**Issue by AddictArts** [wbuchwalter/ng-redux#50]
This will mean react 0.14 and react-dom. Another option is the chrome extension in the web store and at https://github.com/zalmoxisus/redux-devtools-extension

**Comment by wbuchwalter** [comment]
Hey,
I just updated the counter sample app to use `redux-devtools@3.x` + `react@0.14` + `babel@6.x`
Thanks.

**Comment by AddictArts** [comment]
Awesome, thank you
