### ISSUE TITLE
$applyAsync at digestMiddleware

### ISSUE THREAD

**Issue by artaommahe** [wbuchwalter/ng-redux#51]
Maybe instead of
```js
if(!$rootScope.$$phase) {
  $rootScope.$apply(next(action));
} else {
  next(action);
}
```
https://github.com/wbuchwalter/ng-redux/blob/master/src/components/digestMiddleware.js#L3

just
```js
$rootScope.$applyAsync(next(action));
```

**Comment by wbuchwalter** [comment]
Wouldn't `$evalAsync` instead of `$applyAsync` avoid some $digest cycles?
Thanks

**Comment by artaommahe** [comment]
http://www.bennadel.com/blog/2751-scope-applyasync-vs-scope-evalasync-in-angularjs-1-3.htm

**Comment by arahansen** [comment]
+1. using `$$phase` is a no-no
