### ISSUE TITLE
Default initialState in 3.2.0 breaks code

### ISSUE THREAD

**Issue by Antontelesh** [wbuchwalter/ng-redux#54]
Assume you had a root reducer that set initial state when called:

```
const initialState = Map();
function reducer (state = Map(), action) {...}
```

When upgrading to 3.2.0 from previous *minor* version, this code breaks, because es6 default parameter no more applied, because state is `{}` by default. It's really a breaking change.

I think, `ng-redux` should not set empty object as default initial state. But that will cause problems with packages that depend on that feature.

**Comment by Antontelesh** [comment]
More on that. I cannot set initial state to `undefined` explicitly in `createStoreWith`.
If I pass `undefined` it's being reassigned in `ng-redux`.

I think we can allow to explicitly set `undefined` as initial state in `createStoreWith`. That could be done with ternary instead of `||` expression:

```
_initialState = initialState ? initialState : {};
```

I can create a PR a bit later if you wish.

**Comment by wbuchwalter** [comment]
Good call... I didn't thought about this use case.
See PR #55, didn't really had time to think it through as I am in a rush, but it should fix the issue I think.
InitialState would only be passed to redux if it is defined.
Let me know what you think.
Thanks.

**Comment by Antontelesh** [comment]
Yes. Seems like that will fix this issue.
Should I close then?

**Comment by wbuchwalter** [comment]
I'll close this when it is actually merged and released (I won't be able to do that before this evening [EST time]).
Thanks

**Comment by Antontelesh** [comment]
Great! Thanks

**Comment by wbuchwalter** [comment]
Released (sooner than expected) under `3.3.0`.

**Comment by Antontelesh** [comment]
Thank you for quick fix.
Just wondering, why not 3.3.1?

**Comment by wbuchwalter** [comment]
No good reason, I will try to be more consistent with semver in the future :)
