### ISSUE TITLE
How to proceed with multiple modules and reducers

### ISSUE THREAD

**Issue by stefanjudis** [wbuchwalter/ng-redux#61]
Hey there - I'm currently evaluating `ng-redux` to bring it into our massive app.

The situation is as follows. 
We ship several different modules providing different parts of the app. I'd like to connect all the data of these via the flux/redux structure.

According to the docs:

```
angular.module('app', [ngRedux])
.config(($ngReduxProvider) => {
    let reducer = combineReducers(reducers);
    $ngReduxProvider.createStoreWith(reducer, ['promiseMiddleware', loggingMiddleware]);
  });
```

I have to define all the reducers upfront in the configuration of the big big `app` module. What I'd like to do is to register several reducers and store parts on the config phases of the different dependency modules. 

Main idea would be that the modules enrich the global state by itself.

This is currently not possible, as only the `createStoreWith` function is provided. 
I'm kind of thinking of a `extendStoreWith` function or something similar. 

Is this totally off track or am I missing something in here?

Thanks for any advice. :bowtie:

**Comment by laurelnaiad** [comment]
You might be able to maintain separate stores and craft a means by which they feed each other. I've been pondering an attempt at this using RxJs to connect them, and isolating them to individual components (ui-router states and directives) so as to "cut" the state tree into separately managed pieces. I have a vague sense that something like this would enable a slightly more angular2-ish model where components never see the parts of the tree that they shouldn't, and actions bubble upwards only as far as they need to. I know this sounds vague... it's still a bit vague in my head.

**Comment by jbalboni** [comment]
@stefanjudis I'm not sure how this applies to your environment, since we use browserify in combination with angular modules, but what I ended up doing was letting dependency modules include a reducer object (i.e. the sort of object you would pass to combineReducers), then merge all of them together at the top level.

So I may have a sub-module like

```
module.exports = angular.module('app.subModule', [])
    .service('ActionCreatorService', require('./some-actions.js'))

module.exports.reducer = require('./reducer');
```

And the top level app has a wrapper function:

```
appUtils.createReduxApp('app.mainApp', [
    require('./subModule')
], require('./appLevelReducerObject.js'))
```

That wrapper takes the list of dependencies, combines all the reducer objects, and does the normal angular.module set up:

```
exports.createReduxApp = function createApp(name, deps, appReducer) {
    var angularDeps = deps.map((dep) => dep.name || dep);
    var reducerMap = deps.reduce((current, dep) => Object.assign({}, current, dep.reducer), appReducer);
    return angular.module(name, angularDeps)
        .config(function reduxConfig($ngReduxProvider) {
            reducer = combineReducers(reducerMap);
            $ngReduxProvider.createStoreWith(reducer);
        });
};
```

This is simplified, but that's the idea. I wrote another wrapper that can be used to merge reducers, but not create a store, for when there's more than one level of module nesting.

**Comment by stefanjudis** [comment]
@jbalboni Oh man - thanks. I was playing around with some abstractions today to fit our structure and this looks pretty good! Didn't come that far today and this saves me a lot of time!

Thanks. :hand:

**Comment by stefanjudis** [comment]
@jbalboni 

Heyo - quick question. 

I'm now starting to test the different sub modules. Do you have also a solution for testing one module then in separation as it has to call `$ngReduxProvider.createStoreWith(reducer);` itself in this case...

Thanks for any advice and ideas. :)

**Comment by jbalboni** [comment]
@stefanjudis We've generally been testing reducers or components not connected to the store so far in our sub modules. I was planning on mocking the $ngRedux service (or the wrapper service we wrote for it) when testing any code that used it, though.
