### ISSUE TITLE
assign vs. extend and immutables

### ISSUE THREAD

**Issue by laurelnaiad** [wbuchwalter/ng-redux#68]
In order to get ng-redux to work with immutable.js, I changed one thing -- I swapped assign out and replaced it with extend:

https://github.com/laurelnaiad/ng-redux/commit/0e8238e7ecf7292f1680ea6478cb9ad395613598#diff-e9375d670627d2f5df250504bf7cfc57

I guess the issue is whether or not your state tree is really and truly plain objects vs. immutables... immutables die during `assign`....

Is there any harm in switching to extend? Could this change go in? Or is this going to wreak havoc with folks who aren't using immutables or terrible in some other way? ;)

**Comment by wbuchwalter** [comment]
Hey,
Sorry for the delay, but I don't have a lot of free time these days.
I don't see any reason why `extends` (a.k.a `assignIn`in lodash) would break anything, this would need a little bit a testing though.
PR welcome :)

**Comment by laurelnaiad** [comment]
@wbuchwalter I've come to the conclusion that battling the redux universe in order to make the root object of the state tree itself immutable is more trouble than it's worth -- there is really no need, in fact, since first-level tree object equality checks can still be done by ref on a mutable root. After some experience, I'd actually say leave as is.

**Comment by wbuchwalter** [comment]
:+1: Thanks for your input!

**Comment by laurelnaiad** [comment]
although I guess if you have a million first-level objects in your state tree... but then you probably have other issues. :)
