### ISSUE TITLE
Default initial state

### ISSUE THREAD

**Issue by Elijen** [wbuchwalter/ng-redux#69]
Creating a store like this `$ngReduxProvider.createStoreWith(myReducer);` causes the reducers receive arguments like this:
```
{ 
   state: {}, 
   action: {type: "@@redux/INIT"}
}
```

This prevents the reducer from returning initial state on the first run like this:
```
if (typeof state === 'undefined') {
   return initialState
}
```

Reducer should be called instead with the following arguments:
```
{ 
   state: undefined, 
   action: {type: "@@redux/INIT"}
}
```

**Comment by Elijen** [comment]
Looks like `dist` is outdated in `3.3.0` and does not include the fix from #55. Using `master` solved the problem.

**Comment by wbuchwalter** [comment]
Thanks for the info, reopening as a reminder to myself to look into that.

**Comment by wbuchwalter** [comment]
`dist` has been updated, let me know if I missed something.
Thanks.
