### ISSUE TITLE
Dispatches called before being bound

### ISSUE THREAD

**Issue by silver2k** [wbuchwalter/ng-redux#72]
Hi,

In the latest version, I'm using
    connect(mapStateToTarget, [mapDispatchToTarget])(target)
But in a number of scenarios - I'm having state changes hit mapStateToTarget before mapDispatchToTarget is bound to the target.
I my case - I issue a dispatch for some http calls when certain state criteria is met - but obviously this blows up if the state is pre-existing, as the dispatch is not bound.

I'm assuming this isn't intended? Or am I doing it wrong?

**Comment by wbuchwalter** [comment]
Hey,
Dispatching an action inside the `mapStateToTarget` function is very likely a bad practice.
The idea with Redux, is that you dispatch an action, which has a very clear set of side effects (inside your action creators), which in turn triggers changes to the state inside reducers. The goal here is that it's very easy for anyone reading your code to understand all the implications of a user action.
If you have actions, that modify the state, which in turn trigger another action, which modify the state, which .... (you see where I am going). It then become very hard to know what is happening, and you end up with the same problems than MVC.

Can you tell me a little bit more about what you are trying to do here? See how we could do that differently.

**Comment by silver2k** [comment]
I see what you mean. But I don't actually see a way forward on responding to state changes unless they're triggered in `mapStateToTarget`. Unless I register some sort of listener to the Angular model - but I'm not sure that gives me any benefit other than increased complexity.

In my scenario:
I have a basic angular form - every time a field is set - I update my state. (Think of it as a bunch of on & off switches)
When certain combinations of fields are set, I need to also go to the backend and get more info for the user. I can easily have my controller dispatch the actions instead, but what would trigger it, both on initialization and update of state?

**Comment by wbuchwalter** [comment]
Interesting.
In action creators you have access to the state, why not create a selector that tells you if the combination is right, and based on that, dispatch immediatly a second action.
e.g:
```javascript
(getState, dispatch) => {
    dispatch({type: 'SOME_ACTION'});
    let isCombinationRight = combinationSelector(getState());
    if(isCombinationRight) {
        aRandomService.getData()
          .then(result => dispatch({type: 'ANOTHER_ACTION', payload: result}));
    }
}
```

Would something like that works for you?

**Comment by wbuchwalter** [comment]
Closing since no news.
Let me know if that still doesn't suits your needs.
