### ISSUE TITLE
Need a way to access the store object

### ISSUE THREAD

**Issue by odbayar** [wbuchwalter/ng-redux#73]
I am migrating my Angular app to React, and I need to retrieve and pass the store object to react-redux.

So, can you guys add a way to retrieve the store object?

**Comment by odbayar** [comment]
I just passed $ngRedux as a store. It seems to work. I guess all the necessary methods are in it.

**Comment by wbuchwalter** [comment]
Yes, `$ngRedux` is defined as:
`assign({}, store, { connect: Connector(store) })`.
